new Vue({
  el: '#app',
  data: {
    showSuperbeg: false,
    showBeg: false,
    showInt: false,
    showAdv: false,
    superbeg: [
      { id: "0ke0qTsSdkE", title: "I Played on a Football Team - Superbeginner Spanish - Personal Stories #39", level: 1500 },
      { id: "1WYNCa9MEQc", title: "My Classmates Made Fun Of Me - Superbeginner Spanish - Personal Stories #31", level: 2000 },
      { id: "49dp2lDULr8", title: "What We Eat And Drink: Spain VS Japan - Superbeginner Spanish - Daily Life #19", level: 2000 },
      { id: "3VkhlKbyfNA", title: "Losses I've Suffered - Superbeginner Spanish - Personal Stories #40", level: 2500 },
      { id: "yA4NQqd9f7w", title: "I Like High Places - Superbeginner Spanish - Random Topics #10", level: 2500 },
      { id: "E7HvBUgmWTQ", title: "I Don't Cook Anymore - Superbeginner Spanish - Daily Life #40", level: 3000 },
      { id: "GJ1xTuIgfCk", title: "Draw Together Challenge - Superbeginner Spanish - Let's Play Games #8", level: 3000 },
      { id: "sJKNQ8R5YTs", title: "How Many There Are Of Things - Superbeginner Spanish - Daily Life #22", level: 3000 },
      { id: "5BXULXkKeG0", title: "More Head Parts - Superbeginner Spanish - Daily Life #24", level: 4000 },
      { id: "Be2vNQ6k-tw", title: "Guess The Animal 2 - Superbeginner Spanish - Let's Play Games #11", level: 4000 },
      { id: "IkxmzZD6_6s", title: "Crying For A Bacon Sandwich - Superbeginner Spanish - Real Stories #7", level: 4000 },
      { id: "JfIR8T_vAoU", title: "Things I Hate - Superbeginner Spanish - Random Topics #9", level: 4000 },
      { id: "jqCTXheDuRo", title: "Carlitos Learns How to Use a Pencil - Superbeginner Spanish - Humor #10", level: 4000 },
      { id: "lU2nuO16PA8", title: "I like tea - Superbeginner Spanish - Daily Life #12", level: 4000 },
      { id: "ObO1CGY_NHI", title: "I Eat - Superbeginner Spanish - Daily Life #11", level: 4000 },
      { id: "tkPvAUZ-HA8", title: "Yerba Mate - Superbeginner Spanish - Latin American Culture #6", level: 4000 },
      { id: "tt3Fw7f7p-U", title: "Going To Bed - Superbeginner Spanish - Daily Life #38", level: 4000 },
      { id: "TvU1vLowwYk", title: "My Head - Superbeginner Spanish - Daily Life #16", level: 4000 },
      { id: "V9lu1hFnbG4", title: "I Didn't Like Coffee - Superbeginner Spanish - Daily Life #20", level: 4000 },
      { id: "VS-f1tESkwQ", title: "More Or Less - Superbeginner Spanish - Random Topics #2", level: 4000 },
      { id: "DB7oOXiP2XQ", title: "What's In My Luggage - Superbeginner Spanish - Tourism & Travel #6", level: 5000 },
      { id: "eoEGZ6KIrNo", title: "Guess The Animal 3 - Superbeginner Spanish - Let's Play Games #15", level: 5000 },
      { id: "UQ4I5eCB__0", title: "Smells Good/Bad - Superbeginner Spanish - Random Topics #3", level: 5000 },
      { id: "E3obf65u6S4", title: "The Rooster And The Pearl - Superbeginner Spanish - Tales #18", level: 6000 },
      { id: "E86huL2LZfw", title: "Things That Disgust Me - Superbeginner Spanish - Random Topics #10", level: 6000 },
      { id: "k3W1n3FK1j8", title: "Pets That I've Had - Superbeginner Spanish - Daily Life #37", level: 6000 },
      { id: "UlsawitQxuA", title: "Sweet And Sour Things - Superbeginner Spanish - Random Topics #9", level: 6000 },
      { id: "_FbnqYbSDkE", title: "How To Make Spanish Omelette - Superbeginner Spanish - Food #6", level: 7000 },
      { id: "Ir3HwBdjNSs", title: "Parts Of The Body - Superbeginner Spanish - Daily Life #25", level: 7000 },
      { id: "jU4qiFl0w4A", title: "Strange Food I've Eaten - Superbeginner Spanish - Food #5", level: 7000 },
      { id: "rsBTodc57H8", title: "The Frog And The Cow - Superbeginner Spanish - Tales #19", level: 7000 },
      { id: "WGby8Zup6Ks", title: "How to Extinguish Fires - Superbeginner Spanish - How-To #5", level: 7000 },
      { id: "ZKNmZBAd8Xg", title: "Large and Small Things - Superbeginner Spanish - Humor #7", level: 7000 },
      { id: "-1ZfKQV5vY0", title: "Fruit And Vegetable Juice - Superbeginner Spanish - Daily Life #21", level: 8000 },
      { id: "kUpKhd3n_8o", title: "[Alcohol references] What's In My Fridge - Superbeginner Spanish - Daily Life #3", level: 8000 },
      { id: "7hO3vRhzerc", title: "The Fox And The Crow - Superbeginner Spanish - Tales #20", level: 10000 }
    ],
    beg: [
      { id: "CRcGrhdGLNI", title: "Social Networks In Spain - Beginner Spanish - Spanish Culture #20", level: 1000 },
      { id: "4nW9Mg-FeZM", title: "How to Flirt with Spanish Girls - Learn Spanish - Love & Relationships #1", level: 1500 },
      { id: "Dgd2oWwUfvg", title: "Álvaro Soler 🎵 - Beginner Spanish - Spanish Artists #4", level: 1500 },
      { id: "iWZcmyx3ooM", title: "Is The World Becoming Worse? - Beginner Spanish - Random Topics #9", level: 1500 },
      { id: "jjQ-nCtcnuE", title: "The UK Incident - Learn Spanish - Personal Stories #12", level: 1500 },
      { id: "LjZK5t4CdYc", title: "Penélope Cruz - Beginner Spanish - Spanish Artists #3", level: 1500 },
      { id: "t8Ojp6OeHGo", title: "Things We Don't Care About - Beginner Spanish - Random Topics #6", level: 1500 },
      { id: "tXIdogdTrXg", title: "The Catalan Independence Referendum 2/2 - Beginner Spanish - Society #8", level: 1500 },
      { id: "XRn4lc-IAro", title: "How I Learned English - Beginner Spanish - Language Learning #1", level: 1500 },
      { id: "-qd4jbP7zJ8", title: "My Weekday Routine - Easy Spanish - Daily Life #2", level: 2000 },
      { id: "0cVv3_BWnTM", title: "We Like Children, But... - Spanish Module 1", level: 2000 },
      { id: "30wVIRjzca4", title: "The Girl On The Bus - Learn Spanish - Real Stories #3", level: 2000 },
      { id: "3TCQb8jjWNU", title: "Channel Presentation (with SUBTITLES)", level: 2000 },
      { id: "6-NRUC6NjdI", title: "The Catalan Independence Referendum 1/2 - Beginner Spanish - Society #7", level: 2000 },
      { id: "7HHECRQXrvo", title: "How I Learn Thai - Beginner Spanish - Language Learning #3", level: 2000 },
      { id: "8pVw88SYS4U", title: "I'm In Thailand! - Beginner Spanish - Personal Stories #19", level: 2000 },
      { id: "AZ89vSPfnkI", title: "Counting Game - Beginner Spanish - Let's Play Games #7", level: 2000 },
      { id: "b8Eera-U9PU", title: "Why Am I In Thailand? - Beginner Spanish - Personal Stories #32", level: 2000 },
      { id: "bF5agcMfDj8", title: "Marriage in Spain 💏❤️💒 - Learn Spanish - Spanish Culture #4", level: 2000 },
      { id: "fciHwgwIetg", title: "TV Show: Cuéntame - Beginner Spanish - TV Shows #5", level: 2000 },
      { id: "gAVvC3PUESY", title: "The DEFINITIVE Way to Learn the Spanish Subjunctive - Beginner Spanish - Language Learning #20", level: 2000 },
      { id: "iN-e06l-SPM", title: "Spain, Healthiest Country - Beginner Spanish - Society #11", level: 2000 },
      { id: "kgpIjHpEBtY", title: "I Moved Apartments - Beginner Spanish - Personal Stories #15", level: 2000 },
      { id: "kt8qw3bkBHk", title: "I Moved Again (To A Really Cool Place) - Beginner Spanish - Personal Stories #23", level: 2000 },
      { id: "LhdtK2ocKiw", title: "Amey's Self-Introduction - Beginner Spanish - Daily Life #32", level: 2000 },
      { id: "N63X4Rz_RmI", title: "3 Superstitions 2 - Learn Spanish - Spanish Culture #9", level: 2000 },
      { id: "OPU8MaF6Ks4", title: "5 Things I Love About Spain - Beginner Spanish - Daily Life #15", level: 2000 },
      { id: "OYF0FqeWyYU", title: "Learn How To Juggle - Learn Spanish - How-To #2", level: 2000 },
      { id: "rL85kt16l7U", title: "How I do language exchange - Learn Spanish", level: 2000 },
      { id: "SCtzJaCUzQQ", title: "Religion in Spain - Learn Spanish - Spanish Culture #11", level: 2000 },
      { id: "WE-nXHTStNc", title: "When Tere Lived in Taiwan - Learn Spanish - Tourism & Travel #5", level: 2000 },
      { id: "wMU2BbW8Ots", title: "[Beg] The Story of Udon the Puppy 🐶 2/2 - Learn Spanish - Tales #10", level: 2000 },
      { id: "XCGyq85d2qc", title: "Evita Perón 👩🏼🇦🇷 - Easy Spanish - Rebel Women #4", level: 2000 },
      { id: "XDgsM_ZEXpk", title: "The Doctor Recommends... - Beginner Spanish - Tales #16", level: 2000 },
      { id: "yR7253-qpxc", title: "The Boy Under The Tree - Spanish Module 1", level: 2000 },
      { id: "zAWodnxqsyA", title: "The Woman and the Coin, a story from Pakistan - Learn Spanish - Tales #6", level: 2000 },
      { id: "zsu4SsEit50", title: "Guess the Character 4 - Beginner Spanish - Let's Play Games #14", level: 2000 },
      { id: "-awhK7yXlfE", title: "Toni's Bizarre Trip - Beginner Spanish - Personal Stories #4", level: 2500 },
      { id: "2gCik1vqXxc", title: "Isabel Allende - Learn Spanish - Rebel Women #5", level: 2500 },
      { id: "2jSBTh3xefc", title: "My Japan Trip: Will I get rides? 🚗🐻🐟 - Learn Spanish - My Japan Trip #2", level: 2500 },
      { id: "4E3vDvSU65Y", title: "My First Kiss - Beginner Spanish - Personal Stories #14", level: 2500 },
      { id: "5bZplBBZRsc", title: "Things I Dream - Beginner Spanish - Daily Life #26", level: 2500 },
      { id: "8X01U32A4D8", title: "I'm going to London! 🇬🇧🎡 - Learn Spanish - Personal Stories #7", level: 2500 },
      { id: "9-YwjIr_QAM", title: "I'm In China! - Beginner Spanish - Personal Stories #28", level: 2500 },
      { id: "95YZt3C2W54", title: "Best Recent Comments! - Beginner Spanish - Q&A #4", level: 2500 },
      { id: "9dwtBjSatvQ", title: "How I Learned French - Beginner Spanish - Language Learning #9", level: 2500 },
      { id: "9Jh-k8C0kY8", title: "Dreaming Spanish Live! Beginner Level", level: 2500 },
      { id: "_a-XJcd7Ibk", title: "Spanish Snacks: Nocilla (1/2)", level: 2500 },
      { id: "_cNi5uNeUzE", title: "I Hurt My Hand - Beginner Spanish - Personal Stories #21", level: 2500 },
      { id: "_x_GfqaNR_o", title: "One ❤ One Not Always Two (2/3) - Beginner Spanish - Series #2", level: 2500 },
      { id: "AlbnYSsGq6c", title: "Trains in Spain: Inside The Train - Beginner Spanish - Society #6", level: 2500 },
      { id: "bgUg-KLK4Kc", title: "A Loud Heart - Beginner Spanish - Real Stories #6", level: 2500 },
      { id: "Ca5O_nXZi4k", title: "Alek Wek - Easy Spanish - Rebel Women #3", level: 2500 },
      { id: "cTFDRTgEiDw", title: "5 Things That Turn Me Off In A Girl - Beginner Spanish - Love & Relationships #5", level: 2500 },
      { id: "cxCHaUCpFS4", title: "Rosalía - Beginner Spanish - Spanish Culture #24", level: 2500 },
      { id: "CYNW8k5K-Aw", title: "La Sagrada Familia ⛪️ - Easy Spanish - Places in Spain #4", level: 2500 },
      { id: "EWK1JBYXmQ4", title: "Best TV Series for Beginners - Beginner Spanish - Language Learning #19", level: 2500 },
      { id: "fbLiI6OI5Pg", title: "A Lost Puppy (2/3) - Beginner Spanish - Tales #25", level: 2500 },
      { id: "HsgdoFQ6e6A", title: "5 things I dislike of living in Spain - Beginner Spanish - Daily Life #13", level: 2500 },
      { id: "joabYzASSyk", title: "Antonio Banderas - Learn Spanish - Spanish Artists #2", level: 2500 },
      { id: "JzAhm6CY7rc", title: "Spanish Snacks: Nocilla (2/2)", level: 2500 },
      { id: "KK-YKag5lbc", title: "The Lovers of Teruel 💏 - Learn Spanish - Spanish Legends #2", level: 2500 },
      { id: "KqL7Jt1pxAI", title: "7 polite and impolite things in Spain - Learn Spanish - Spanish Culture #7", level: 2500 },
      { id: "KQrUwFTsryI", title: "The Shoes of the Happy Man 👞 - Learn Spanish - Tales #2", level: 2500 },
      { id: "LeRejUPVUc4", title: "What things is she embarrassed of? - Spanish Module 1", level: 2500 },
      { id: "lZIkCTcRCxM", title: "❤️❤️ My 4 School Loves ❤️❤️ - Learn Spanish - Personal Stories #9", level: 2500 },
      { id: "mI9RCNPQnAg", title: "Tere is visiting Barcelona - Beginner Spanish - Tourism & Travel #4", level: 2500 },
      { id: "MvRiaMceOag", title: "[Beg] How To Flirt - Learn Spanish - Humor #5", level: 2500 },
      { id: "NAfng34PdQ8", title: "How To Attract A Spanish Guy - Beginner Spanish - Love & Relationships #3", level: 2500 },
      { id: "ofViSC86a7U", title: "Sonia & Alberto's Ideal House - Beginner Spanish - Daily Life #39", level: 2500 },
      { id: "OzxGXKiPJew", title: "Adventure in the Amazon - Beginner Spanish - Personal Stories #35", level: 2500 },
      { id: "PEIMwS5STnQ", title: "[Beg] Movietalk! Los Serrano 📺 - Learn Spanish - Movietalk #1", level: 2500 },
      { id: "rfmeuL1eRtI", title: "Fallas of Valencia - Easy Spanish - Spanish Festivals #3", level: 2500 },
      { id: "rFY9gZBfIBk", title: "Pranking The Librarian - Beginner Spanish - Personal Stories #2", level: 2500 },
      { id: "rsWfs3f6dq0", title: "The Conflict of Two Families - Learn Spanish - Tales #4", level: 2500 },
      { id: "RyuMgGBChxk", title: "One ❤ One Not Always Two (3/3) - Beginner Spanish - Series #3", level: 2500 },
      { id: "S2U0xbXFTJo", title: "Adrià's problems in China - Beginner Spanish - Personal Stories #11", level: 2500 },
      { id: "T-xdIVejWEE", title: "Things We Do Often - Spanish Module 1", level: 2500 },
      { id: "uk2UlMKFLP8", title: "Sports: 🏋 My Workout Routine 🏋", level: 2500 },
      { id: "V6Z4i0R_yfI", title: "Nuria's Love Story - Beginner Spanish - Love & Relationships #6", level: 2500 },
      { id: "v_C9_BVYBS4", title: "Guess The Character 3 - Beginner Spanish - Let's Play Games #10", level: 2500 },
      { id: "WsVJRkMjD1g", title: "Adrià's House - Learn Spanish - Daily Life #9", level: 2500 },
      { id: "XhtPRy-dpus", title: "6 Types Of Couples - Beginner Spanish - Love & Relationships #4", level: 2500 },
      { id: "yJSSGrzTmvk", title: "5 Spots You Can't Miss In Barcelona - Beginner Spanish - Tourism & Travel #8", level: 2500 },
      { id: "yYqIdySAoQY", title: "Luna likes guys that are... - Spanish Module 1", level: 2500 },
      { id: "8ZrKYEeNPqM", title: "Things That Embarrass Us - Beginner Spanish - Society #10", level: 3000 },
      { id: "99EYCQpXvXc", title: "I Lost My Flight 😭 - Beginner Spanish - Personal Stories #27", level: 3000 },
      { id: "_Zak5NEepUc", title: "Enigma: Water And Glass - Beginner Spanish - Let's Play Games #9", level: 3000 },
      { id: "AJO7AEPPTzM", title: "Cheap And Expensive Things In Spain - Beginner Spanish - Daily Life #29", level: 3000 },
      { id: "Aozn4tY7IiE", title: "Questions & Answers! - Beginner Spanish - Q&A #1", level: 3000 },
      { id: "BpZqms-jjm8", title: "🚴 Alfonsina Strada 🚴 - Easy Spanish - Rebel Women #1", level: 3000 },
      { id: "DeaosXADYZM", title: "Leo Messi 🇦🇷⚽️ - Learn Spanish - Sports #4", level: 3000 },
      { id: "fwVDqDZvHGs", title: "Spanish News: Ferry tragedy and ETA 🛥🔫💣", level: 3000 },
      { id: "guUWm99k9Hg", title: "Los Serrano 📺👨‍👩‍👧‍👦🏫💑 - Learn Spanish - TV Shows #4", level: 3000 },
      { id: "H-33l8JYNww", title: "Football Club Barcelona - Learn Spanish - Sports #5", level: 3000 },
      { id: "HpxCXr_wmlA", title: "Snowboarding Without Enough Cash - Beginner Spanish - Personal Stories #1", level: 3000 },
      { id: "hvXMnDbqkRw", title: "Day of Sant Jordi 🌹❤️📖 - Easy Spanish - Spanish Festivals #6", level: 3000 },
      { id: "JbLD0dpbGl0", title: "Luna Likes To Eat - Spanish Module 1", level: 3000 },
      { id: "jm6yMmYg824", title: "The Potato Incident 🔥 - Learn Spanish - Personal Stories #13", level: 3000 },
      { id: "jxPphVwU8jQ", title: "They Forgot Me - Beginner Spanish - Personal Stories #20", level: 3000 },
      { id: "kC88flvMR6M", title: "We have long school trips! - Learn Spanish - Spanish Culture #2", level: 3000 },
      { id: "krMBTJGWmAs", title: "The First Kiss 😘 - Learn Spanish - Love & Relationships #2", level: 3000 },
      { id: "m0lSxHO_2JE", title: "[Beg] The Story of Udon the Puppy 🐶 1/2 - Learn Spanish - Tales #10", level: 3000 },
      { id: "mnIbPRFY52A", title: "Picasso and the Guernica 🎨 - Learn Spanish - Spanish Artists #1", level: 3000 },
      { id: "R6A0LOhLPD4", title: "Running with the bulls: Sanfermines - Easy Spanish - Spanish Festivals #2", level: 3000 },
      { id: "RJ4tnGxzCdM", title: "Manolito Gafotas #3 📖 - Learn Spanish - Books #3", level: 3000 },
      { id: "S6w7AXeJ9Z0", title: "Sonia's Things Got Stolen - Beginner Spanish - Personal Stories #30", level: 3000 },
      { id: "S7lOCHIP43o", title: "Correfocs - Easy Spanish - Spanish Festivals #4", level: 3000 },
      { id: "S7uoObpxTAU", title: "Fable Of The Wolf And The Dog - Beginner Spanish - Tales #22", level: 3000 },
      { id: "swKTi6FQgA0", title: "The Wine Battle 🍷 - Learn Spanish - Spanish Festivals #9", level: 3000 },
      { id: "tKcmOuITBI4", title: "Legend of La Llorona - Learn Spanish - Legends #6", level: 3000 },
      { id: "uJKrkVI-SKM", title: "Guess The Character 2 - Beginner Spanish - Let's Play Games #6", level: 3000 },
      { id: "WekEN6S5-S0", title: "Verano Azul TV Series 🌊☀️ - Easy Spanish - TV Shows #1", level: 3000 },
      { id: "wimILH11p1A", title: "Legend of The Butterfly - Learn Spanish - Spanish Legends #4", level: 3000 },
      { id: "YMOpKHr9R-Y", title: "My Family - Beginner Spanish - Daily Life #36", level: 3000 },
      { id: "Z3DqGtd-1iw", title: "Surprise Inside A Console - Beginner Spanish - Real Stories #8", level: 3000 },
      { id: "ZjZ-nsldbbg", title: "The Broken Plane Engine - Beginner Spanish - Tales #11", level: 3000 },
      { id: "ZuiAXRU0Xvc", title: "Two Naughty Brothers - Beginner Spanish - Tales #13", level: 3000 },
      { id: "0fUND1V1Pns", title: "[+18 Swearing] News: 2 Small Things With Big Consequences - Beginner Spanish - News #6", level: 4000 },
      { id: "0H8beh6uZTA", title: "The Angry Wife - Beginner Spanish - Tales #12", level: 4000 },
      { id: "0T9Eo31UvGg", title: "Why Do Clouds Float? - Beginner Spanish - Why? #1", level: 4000 },
      { id: "2jkHB6N39ZA", title: "Football in my childhood ⚽️⚽️ - Learn Spanish - Sports #3", level: 4000 },
      { id: "3jecynjbnj0", title: "Love Story In The Train - Beginner Spanish - Personal Stories #24", level: 4000 },
      { id: "_Mk6WYi90O8", title: "Boston VS Barcelona - Beginner Spanish - Daily Life #31", level: 4000 },
      { id: "aBNCxpbK-oE", title: "All Saints' Day/Día de los Muertos - Learn Spanish - Festivals #15", level: 4000 },
      { id: "B1U63X3Ip1g", title: "3 Spanish Superstitions 1 - Learn Spanish - Spanish Culture #8", level: 4000 },
      { id: "bP6T6VmlEcg", title: "Amey Likes Australia - Beginner Spanish - Tourism & Travel #11", level: 4000 },
      { id: "brFfI-7F9Gg", title: "The Devil's Cross - Learn Spanish - Spanish Legends #3", level: 4000 },
      { id: "bu0uq4tJCrQ", title: "4 Childhood Games  - Learn Spanish - Spanish Culture #10", level: 4000 },
      { id: "DW-qcKk4b-A", title: "The Conflict Between Catalonia and Spain - Learn Spanish - Society #1", level: 4000 },
      { id: "DyVndbnDXIM", title: "The Sleepover - Beginner Spanish - Tales #14", level: 4000 },
      { id: "EAVXqUFEaSE", title: "[Beg] Minecraft 3: Finally A House! - Learn Spanish - Video Games #4", level: 4000 },
      { id: "Fn3eCiyoadQ", title: "Spicy Chemical Attack - Learn Spanish - Real Stories #2", level: 4000 },
      { id: "gS-ZnVMAgTQ", title: "Tere's Home - Beginner Spanish - Daily Life #6", level: 4000 },
      { id: "h0fxU7slq00", title: "We Protested In High School - Beginner Spanish - Personal Stories #25", level: 4000 },
      { id: "HAsxjfKwbTA", title: "Trains in Spain: The Station - Beginner Spanish - Society #5", level: 4000 },
      { id: "he7x8sVKB-4", title: "🎞 Guess The Movie 2! 🎞 - Learn Spanish - Games #3", level: 4000 },
      { id: "HuQTMUZhalQ", title: "Where Did The Cheese Come From? - Beginner Spanish - Tales #17", level: 4000 },
      { id: "I7jI90Ukhp0", title: "Baby Jumping Festival - Beginner Spanish - Festivals #21", level: 4000 },
      { id: "igcl-mb67lc", title: "Animals We Like - Beginner Spanish - Random Topics #8", level: 4000 },
      { id: "JgCiIEPD9RQ", title: "Getting around in Barcelona 🚇🚴🚠 - Easy Spanish - Daily Life #4", level: 4000 },
      { id: "JqPUbzZPybI", title: "🎞 Guess The Movie 🎞 - Learn Spanish - Games #1", level: 4000 },
      { id: "K5RkLfHoKho", title: "Christmas Lottery! - Learn Spanish - Spanish Culture #12", level: 4000 },
      { id: "kJJRzjYILmQ", title: "The Original Story of Cinderella 4/5 - Learn Spanish - Tales #9", level: 4000 },
      { id: "kJxH1Ivyc7w", title: "Daisy's Vengeance (1/2) - Beginner Spanish - Personal Stories #3", level: 4000 },
      { id: "l0d1IWDV_eo", title: "Story Game: Once Upon a Time - Beginner Spanish - Let's Play Games #12", level: 4000 },
      { id: "L2EOjYQ-i4U", title: "A Lost Puppy (3/3) - Beginner Spanish - Tales #25", level: 4000 },
      { id: "LghAHenU6is", title: "Guess The Character 5 - Beginner Spanish - Let's Play Games #15", level: 4000 },
      { id: "N2n2ZxqYaxk", title: "Things That Happen In School - Beginner Spanish - Humor #6", level: 4000 },
      { id: "np8bQxtiNzI", title: "[Beg] Manolito Gafotas - Learn Spanish - Books #1", level: 4000 },
      { id: "O2R_Lr8_3e4", title: "3 Times I Hurt My Head - Beginner Spanish - Personal Stories #32", level: 4000 },
      { id: "oKhRfHziMWQ", title: "Alicia Alonso 💃🇨🇺 - Learn Spanish - Rebel Women #6", level: 4000 },
      { id: "PAZ_ukX6V-Y", title: "The Origin Of Numbers - Beginner Spanish - Random Topics #7", level: 4000 },
      { id: "PdyUzmz_t0g", title: "Danger in Bosnia - Beginner Spanish - Personal Stories #22", level: 4000 },
      { id: "pExyq22iyp8", title: "6 things that surprise Spaniards about the US - Learn Spanish - Society #3", level: 4000 },
      { id: "Pxnx8Ndketg", title: "Castellers 🎺🏰🎆 - Learn Spanish - Spanish Festivals #5", level: 4000 },
      { id: "q7DdXbWwjf4", title: "Sports: Went to the Climbing Gym", level: 4000 },
      { id: "rVhKBp3_gIs", title: "News About 2 Women - Beginner Spanish - News #4", level: 4000 },
      { id: "UAivyfpW3oY", title: "Minecraft #2: Making a Bed - Learn Spanish - Video Games #2", level: 4000 },
      { id: "UsbnZtT-Cwg", title: "Doraemon - Learn Spanish - TV Shows #3", level: 4000 },
      { id: "UWTQBxW4fYQ", title: "Shopping for Clothes in Spain 👕👚 - Learn Spanish - Daily Life #8", level: 4000 },
      { id: "uzkYOrz2BE4", title: "Spanish Comics - Beginner Spanish - Spanish Culture #17", level: 4000 },
      { id: "Vo5yJi7Obdw", title: "One Apple A Day - Spanish Module 1", level: 4000 },
      { id: "vZJvtJtQUBU", title: "The Original Story of Cinderella 1/5 - Learn Spanish - Tales #9", level: 4000 },
      { id: "YoBvtmQCImc", title: "Cálico Electrónico, The Internet Series - Beginner Spanish - Spanish Culture #22", level: 4000 },
      { id: "yoTs6T9Grms", title: "Surprise At The Top Of The Mountain - Learn Spanish - Real Stories #5", level: 4000 },
      { id: "z8scL1Y-3pU", title: "Adrià and the Armchair (1/2) - Beginner Spanish - Personal Stories #10", level: 4000 },
      { id: "-Bl3KZdbBkc", title: "[Beg] 5 Party Tricks! - Learn Spanish - How-To #3", level: 5000 },
      { id: "-mgWetSaOiQ", title: "Spanish Coins & Bills - Beginner Spanish - Daily Life #27", level: 5000 },
      { id: "0rouzLiZjLA", title: "Tomato Festival: 🍅 La Tomatina 🍅 - Easy Spanish - Spanish Festivals #1", level: 5000 },
      { id: "6SlLxHGbcyk", title: "Movietalk: Los Serrano #2 📺 - Beginner Spanish - Movietalk #2", level: 5000 },
      { id: "9fftjGOIHBs", title: "Vlogging like 🕶 Casey Neistat 🕶 - Learn Spanish - Humor #4", level: 5000 },
      { id: "_xjIhySycs0", title: "Personal Story: Cooking Potatoes", level: 5000 },
      { id: "AkL8zcv3OsI", title: "🌹 Legend of Sant Jordi 🌹 - Learn Spanish - Spanish Legends #1", level: 5000 },
      { id: "aNLvqGFP05I", title: "Tere's hometown in Mexico - Beginner Spanish - Tourism & Travel #3", level: 5000 },
      { id: "AX3wz1E_etc", title: "The Kimchi Disaster - Beginner Spanish - Personal Stories #42", level: 5000 },
      { id: "BdXQq1gz-RQ", title: "SpaceX - Beginner Spanish - Random Topics #4", level: 5000 },
      { id: "BeFw8AyO8BY", title: "Artist Frida Kahlo - Easy Spanish - Rebel Women #2", level: 5000 },
      { id: "BywjrgVItKE", title: "I Traveled to Morocco as a Kid 🐫🏜 - Learn Spanish - Personal Stories #6", level: 5000 },
      { id: "C2_fWEcWD1o", title: "5 Spanish Inventions - Learn Spanish - Society #4", level: 5000 },
      { id: "C6f4AP7Pr6A", title: "Spanish Cartoons - Beginner Spanish - Spanish Culture #14", level: 5000 },
      { id: "Cf5Dnp5p3Fs", title: "I Failed my First Aid Exam - Beginner Spanish - Personal Stories #37", level: 5000 },
      { id: "CW3XngEJlR8", title: "Languages Of Mexico - Beginner Spanish - Latin American Culture #4", level: 5000 },
      { id: "D5IbyCpxZps", title: "The Basement - Learn Spanish - Horror Stories #1", level: 5000 },
      { id: "deLo5_E_0qk", title: "Game of Thrones! (*I've never watched it) - Learn Spanish - Humor #3", level: 5000 },
      { id: "eEC25PrUoM8", title: "I Got Eye Surgery - Beginner Spanish - Personal Stories #41", level: 5000 },
      { id: "eEP5_Be_HHs", title: "The Original Story of Cinderella 2/5 - Learn Spanish - Tales #9", level: 5000 },
      { id: "Fq2mX3DALps", title: "Machu Picchu - Beginner Spanish - Latin American Culture #5", level: 5000 },
      { id: "FwtoO7OF_RY", title: "The Pooping Log 🎄💩 - Learn Spanish - Spanish Festivals #10", level: 5000 },
      { id: "g-viJ_rboZs", title: "The Spanish Card Deck - Beginner Spanish - Spanish Culture #19", level: 5000 },
      { id: "g3k7xGDaDXI", title: "Adrià and the Armchair (2/2) - Beginner Spanish - Personal Stories #10", level: 5000 },
      { id: "Gj3a7-SOVCE", title: "Carnival - Learn Spanish - Spanish Festivals #11", level: 5000 },
      { id: "iI5M1pbiESc", title: "Game: Things That Come In Pairs - Spanish Module 1", level: 5000 },
      { id: "l16DRMvPoKY", title: "Spanish Civil War 🇪🇸🔫💣 - Learn Spanish - History #1", level: 5000 },
      { id: "L9MewE0Pu5s", title: "Spanish Snacks: El Bollycao", level: 5000 },
      { id: "LBPpsY9SlwQ", title: "Let's Play Minecraft! - Learn Spanish - Video Games #1", level: 5000 },
      { id: "lSO6zRrzdmo", title: "Worry Dolls - Beginner Spanish - Latin American Culture #1", level: 5000 },
      { id: "moqW6Dvw3bs", title: "Bad driving and eating mucus - Learn Spanish - News #2", level: 5000 },
      { id: "mZigjtUcwDI", title: "Childhood Games #2 - Learn Spanish - Spanish Culture #13", level: 5000 },
      { id: "nKQu7mf1qpY", title: "Guess the Animal! 🐶🐱🐴-- Learn Spanish - Games #2", level: 5000 },
      { id: "Q__ipSNtJJk", title: "Accident In The Restaurant - Beginner Spanish - Personal Stories #29", level: 5000 },
      { id: "R9BQBDd6qB8", title: "True Wealth - Learn Spanish - Tales #3", level: 5000 },
      { id: "rcwoUHaemRU", title: "Does Luna Like Green Things? - Spanish Module 1", level: 5000 },
      { id: "RLhI98LPrys", title: "Christmas Eve and Christmas Day - Learn Spanish - Festivals #17", level: 5000 },
      { id: "RQWpdFap_oM", title: "The Fisherman And His Wife - Learn Spanish - Tales #8", level: 5000 },
      { id: "S9SHb2VPmKw", title: "That time I stole - Learn Spanish - Personal Stories #8", level: 5000 },
      { id: "SHMwxujHLsw", title: "News: Bad Man, Strong Man - Beginner Spanish - News #5", level: 5000 },
      { id: "VG2z1qUEcg8", title: "Monkeys! Monkeys! Monkeys! 🙈🙊🙉 - Beginner Spanish - Random Topics #1", level: 5000 },
      { id: "w0109AUJ4tQ", title: "El Camino de Santiago ⛪️🐚🚶🏻 - Easy Spanish - Places in Spain #3", level: 5000 },
      { id: "W6fHn6K_U-g", title: "Eating Fruit in Thailand - Beginner Spanish - Food #4", level: 5000 },
      { id: "Xcs2cB9bp6M", title: "Christmas in Spain - Learn Spanish - Festivals #16", level: 5000 },
      { id: "xIQeZtMdXhQ", title: "4 Best Unknown Spots In Spain - Beginner Spanish - Tourism & Travel #7", level: 5000 },
      { id: "XSRvamU8ym4", title: "How to Make Juggling Balls - Learn Spanish - How-To #1", level: 5000 },
      { id: "zHcTH-X7g-c", title: "The Original Story of Cinderella 5/5 - Learn Spanish - Tales #9", level: 5000 },
      { id: "znKBzgzA530", title: "Mountain of Montserrat 🏔🚠 - Easy Spanish - Places in Spain #1", level: 5000 },
      { id: "zwL7a5SQk3g", title: "🎆🎆 San Juan 🎆🎆 - Learn Spanish - Spanish Festivals #13", level: 5000 },
      { id: "-lrG4UvSKL0", title: "New Year's Eve - Learn Spanish - Festivals #18", level: 6000 },
      { id: "03qF-uHXQCg", title: "My House - Easy Spanish - Daily Life #1", level: 6000 },
      { id: "3YeoCAsZDm0", title: "The Origin of the Name of Spain - Beginner Spanish - Spanish Culture #26", level: 6000 },
      { id: "7dm8IyWUxUM", title: "Daisy's Vengeance (2/2) - Beginner Spanish - Personal Stories #3", level: 6000 },
      { id: "_e0ne8WSoG8", title: "Toni travels to Thailand - Beginner Spanish - Tourism & Travel #2", level: 6000 },
      { id: "aOOtiIiaih0", title: "The monk and the garden - Learn Spanish - Tales #7", level: 6000 },
      { id: "aWSsWoWyJIs", title: "Spain's Coat of Arms - Beginner Spanish - Spanish Culture #25", level: 6000 },
      { id: "bWW2ZeWSrjc", title: "Drinks We Like - Beginner Spanish - Daily Life #33", level: 6000 },
      { id: "CtL7NzElloM", title: "El Coco 👻 - Beginner Spanish - Spanish Culture #23", level: 6000 },
      { id: "d8tRz4ndAA8", title: "The Fox And The Grapes - Beginner Spanish - Tales #23", level: 6000 },
      { id: "deJ45JfGV6M", title: "Manolito Gafotas #2 📖 - Learn Spanish - Books #2", level: 6000 },
      { id: "E4lnGUjD7KM", title: "The Girl And The Dragon - Spanish Module 1", level: 6000 },
      { id: "Gv9UM_KHlp4", title: "Pig slaughter 🐷 - Learn Spanish - Spanish Culture #5", level: 6000 },
      { id: "GYtiAdJyyEQ", title: "Riviera Maya - Beginner Spanish - Tourism & Travel #9", level: 6000 },
      { id: "IRuHHaVTGr0", title: "Turrón and Other Christmas Sweets - Learn Spanish - Festivals #19", level: 6000 },
      { id: "LZs226vWBto", title: "The Fable Of The Rabbits And The Frogs - Beginner Spanish - Tales #21", level: 6000 },
      { id: "m0x1pQ9SMUY", title: "We Don't Have A Tooth Fairy - Beginner Spanish - Spanish Culture #16", level: 6000 },
      { id: "nUJj6h-Eirs", title: "Spanish Santa Claus - Easy Spanish - Spanish Festivals #7", level: 6000 },
      { id: "poP5P0oMFyk", title: "A Bad Decision - Learn Spanish - Tales #4", level: 6000 },
      { id: "sLpbZoO_h8o", title: "A Lost Puppy (1/3) - Beginner Spanish - Tales #25", level: 6000 },
      { id: "UA-JHkm5k6Q", title: "The 5 Looks of Spanish Girls - Learn Spanish - Humor #2", level: 6000 },
      { id: "UOszbogNOSY", title: "Players To The Ground! - Beginner Spanish - News #7", level: 6000 },
      { id: "2WwIur2U_gA", title: "The Boy Who Ate 2 Of Each - Spanish Module 1", level: 7000 },
      { id: "7lnTaAwSQI0", title: "The Basque Country - Beginner Spanish - Places in Spain #7", level: 7000 },
      { id: "8MctDxH8uCA", title: "My Skateboard Got Run Over! - Beginner Spanish - Personal Stories #17", level: 7000 },
      { id: "EkmTwV6qcAk", title: "My First Grey Hair 👴🏼 - Learn Spanish - Personal Stories #5", level: 7000 },
      { id: "iGzr4XBsJnA", title: "Differences Between Canary Islands And Barcelona - Beginner Spanish - Places In Spain #8", level: 7000 },
      { id: "iuMLYwbWY0k", title: "My Favorite TV Series - Beginner Spanish - Random Topics #5", level: 7000 },
      { id: "JuldUFwxmeQ", title: "Don Quixote - Beginner Spanish - Spanish Culture #21", level: 7000 },
      { id: "mSdFwbSu7qg", title: "Throwing a Goat Off a Tower 🐐😱 - Learn Spanish - Spanish Festivals #12", level: 7000 },
      { id: "MzjBDRDQoQo", title: "The 😞😤😡 Goat - Beginner Spanish - Humor #8", level: 7000 },
      { id: "NMowjjiiPIA", title: "House Intruders 🐜 - Beginner Spanish - Daily Life #17", level: 7000 },
      { id: "o0J5O-Pc-Vk", title: "Island of Mallorca 🏝🌞 - Easy Spanish - Places in Spain #2", level: 7000 },
      { id: "r2lxofUusQA", title: "Easter Holiday - Learn Spanish - Spanish Festivals #8", level: 7000 },
      { id: "Td6mqDNTn1I", title: "I Eat Insects - Beginner Spanish - Tourism & Travel #12", level: 7000 },
      { id: "uuUVceNOJxU", title: "🌹🐸 The Rose and the Toad 🐸🌹 - Learn Spanish - Tales #5", level: 7000 },
      { id: "vU74g3XHHb8", title: "The 5 looks of Spanish Guys - Learn Spanish - Humor #1", level: 7000 },
      { id: "ZD4qivbJdg4", title: "The Legend Of Maize - Beginner Spanish - Legends #7", level: 7000 },
      { id: "43b0VChp2Oo", title: "Our Favorite Mexican Food - Beginner Spanish - Food #8", level: 8000 },
      { id: "_S8ufJOWIQ0", title: "Game: Think Of Green Food - Spanish Module 1", level: 8000 },
      { id: "HaV26WoqHqM", title: "Ricardo's Fridge - Beginner Spanish - Daily Life #28", level: 8000 },
      { id: "ifm0B9KmIzk", title: "My 5 favorite Spanish dishes 🍅🐙🍞 - Learn Spanish - Food #3", level: 8000 },
      { id: "JHN2DSm4ig8", title: "[Alcohol references] Adrià's Fridge - Beginner Spanish - Daily Life #10", level: 8000 },
      { id: "neAE2pZYEg8", title: "Tere's breakfast as a child - Beginner Spanish - Daily Life #7", level: 8000 },
      { id: "NJfBnZingLg", title: "How to Put a Giraffe in a Fridge? - Beginner Spanish - Humor #9", level: 8000 },
      { id: "olTZ-YlKL00", title: "The Caganer - Learn Spanish - Spanish Culture #3", level: 8000 },
      { id: "R8GQuL2mxHI", title: "Things She Likes To Drink - Spanish Module 1", level: 8000 },
      { id: "rJiKddWL7Yg", title: "The Sick Hamster - Learn Spanish - Real Stories #4", level: 8000 },
      { id: "FmYLuH5Pl5U", title: "The Canary Islands - Beginner Spanish - Places in Spain #6", level: 10000 },
      { id: "h1ALm3U2qP8", title: "Tapas! 🍤🧀🐟 - Learn Spanish - Food #2", level: 10000 },
      { id: "ncC4IzIin4k", title: "Flamenco Music 💃💃 - Learn Spanish - Spanish Culture #1", level: 10000 },
      { id: "rJGXV9xguj4", title: "4 Favorite Places in Spain - Beginner Spanish - Tourism & Travel #13", level: 10000 },
      { id: "uQAqK7geOWs", title: "The Lost Scarf - Beginner Spanish - Personal Stories #18", level: 10000 },
      { id: "z_e6fsLKNo0", title: "The Frog and the Scorpion 🐸🦂 - Easy Spanish - Tales #1", level: 10000 },
      { id: "8A4bq6MnDkw", title: "Food in my Cabinet 🍌🍞🍿🍊 - Easy Spanish - Daily Life #5", level: 12000 },
      { id: "S1eUCjQJECU", title: "The Original Story of Cinderella 3/5 - Learn Spanish - Tales #9", level: 12000 },
      { id: "1PDZdjkNJ6w", title: "Christmas Songs in Spain - Learn Spanish - Festivals #20", level: 15000 },
      { id: "3qlOpMdlXd0", title: "The Letter Z - Beginner Spanish - The Alphabet #2", level: 15000 },
      { id: "wGjZu7Y-cJg", title: "Paella - Easy Spanish - Food #1", level: 15000 },
      { id: "gDbX0qL73Jg", title: "5 weird things about Spain 1/2 - Learn Spanish - Spanish Culture #6", level: 20000 },
      { id: "UyVQy54idHs", title: "[Beg] The Hitchhiker Story - Learn Spanish - Real Stories #1", level: 37000 }
    ],
    int: [
      { id: "0mUnZTFr90Y", title: "The Death Penalty: Good or Bad? - Intermediate Spanish - Discussion #1", level: 1500 },
      { id: "9CbO6itOMZE", title: "How I Got Into Languages - Intermediate Spanish - Personal Stories #34", level: 1500 },
      { id: "9DzjOoIq0pQ", title: "Count Hours, Not Years - Intermediate Spanish - Language Learning #22", level: 1500 },
      { id: "o6lGPH_AIhE", title: "One Big Reason Speaking Practice is Not Important - Intermediate Spanish - Language Learning #16", level: 1500 },
      { id: "O7KWDbeE830", title: "Watch Series, Not Movies - Fast Intermediate - Language Learning #13", level: 1500 },
      { id: "v7BG4xLVGDE", title: "My Dream For This Channel - Intermediate Spanish - Language Learning #4", level: 1500 },
      { id: "1U-Hy0Bf_Ro", title: "How I Managed To Forgive - Intermediate Spanish - Personal Stories #33", level: 2000 },
      { id: "4PCKqEgiK_A", title: "Story Of 3 Friends Reunited - Intermediate Spanish - Personal Stories #26", level: 2000 },
      { id: "9kNC_rhXMoE", title: "Debate: ❤️❤️ National or International Marriage ❤️❤️ - Intermediate Spanish - Debates #3", level: 2000 },
      { id: "AdWG63kHRgc", title: "Why I Don't Write In My Videos - Intermediate Spanish - Language Learning #10", level: 2000 },
      { id: "DAVSKj1RebY", title: "The Best Spanish Web Series - Intermediate Spanish - Spanish Culture #27", level: 2000 },
      { id: "epELAYk5CoA", title: "Success Cases in Language Learning - Intermediate Spanish - Language Learning #24", level: 2000 },
      { id: "gFuA_6JdOZQ", title: "Why I Don't Correct People - Intermediate Spanish - Language Learning #5", level: 2000 },
      { id: "IJo4SJhn08w", title: "The Best Way To Learn Spanish - Intermediate Spanish - Language Learning #6", level: 2000 },
      { id: "j6FNRpraWwM", title: "The Plateau Is a Myth - Intermediate Spanish - Language Learning #12", level: 2000 },
      { id: "jqiJz7wSC5k", title: "A Word Is Not A Translation - Intermediate Spanish - Language Learning #8", level: 2000 },
      { id: "KTOPh7f32Qg", title: "Dreaming Spanish Live! Intermediate Level [links to topics in the description]", level: 2000 },
      { id: "lHXVYe-zu6M", title: "You Should Wait To Start Speaking - Intermediate Spanish - Language Learning #11", level: 2000 },
      { id: "OheGJ2geFnA", title: "Why to do Extensive Reading (When You're Ready) - Intermediate Spanish - Language Learning #14", level: 2000 },
      { id: "RBAn4iWCBSE", title: "The Worst Spanish Person - Intermediate Spanish - Society #12", level: 2000 },
      { id: "s1rXXMDSJvg", title: "Questions & Answers 2 - Intermediate Spanish - Q&A #3", level: 2000 },
      { id: "Tm2ou3ZRlAY", title: "Alita, Movie Review - Intermediate Spanish - Movie Reviews #1", level: 2000 },
      { id: "y7qEOhbixpQ", title: "Do What You're Ready For - Intermediate Spanish - Language Learning #7", level: 2000 },
      { id: "1b3EEcA1BXA", title: "Scene: At The Doctor - Intermediate Spanish - Scenes #2", level: 2500 },
      { id: "7O3mcz_zmBY", title: "Mexico DF - Intermediate Spanish - Tourism & Travel #14", level: 2500 },
      { id: "_4lwte7HrWE", title: "Slang and Swearwords Intermediate Course with Adrià! (link in the description)", level: 2500 },
      { id: "DpU-B3mLCTY", title: "Don't Cry Challenge - Intermediate Spanish - Challenges #1", level: 2500 },
      { id: "jSA3S5AJAcs", title: "Spanish Town Festivals - Intermediate Spanish - Spanish Culture #18", level: 2500 },
      { id: "KbXqpm_IJG8", title: "Guess the Character - Intermediate Spanish - Games #4", level: 2500 },
      { id: "N3ySegvjArw", title: "Captain Marvel, Movie Review - Intermediate Spanish - Movie Reviews #2", level: 2500 },
      { id: "s-cuZVyjcjg", title: "Things YOU Like, Replies to My Question - Intermediate Spanish - Q&A #2", level: 2500 },
      { id: "sxynQvaYT8c", title: "I'm in Hong Kong! - Intermediate Spanish - Tourism & Travel #16", level: 2500 },
      { id: "tvrS3Gky3v0", title: "Debate: Flying VS Invisibility - Intermediate Spanish - Debates #2", level: 2500 },
      { id: "z_4eRACVbII", title: "Why Pronunciation Matters - Intermediate Spanish - Language Learning #23", level: 2500 },
      { id: "zmh1IsoVVUk", title: "Beach VS Mountain - Intermediate Spanish - Debates #5", level: 3000 },
      { id: "5EeTaxer8a4", title: "History Of Spain: The Catholic Monarchs - Intermediate Spanish - History #7", level: 3000 },
      { id: "_795JpL0nMo", title: "Mexico VS Thailand - Intermediate Spanish - Tourism & Travel #15", level: 3000 },
      { id: "jIUeHVLPZd0", title: "La Casa de Papel, Episode 1 Explained - Intermediate Spanish - TV Shows #6", level: 3000 },
      { id: "3vPO3-ApVrc", title: "Spanish History: The Spanish Empire - Intermediate Spanish - History #9", level: 4000 },
      { id: "au5BhDHXnZA", title: "Scary Things 👻 - Intermediate Spanish - Daily Life #18", level: 4000 },
      { id: "ctlvuCr7Oa8", title: "The Royal Family - Intermediate Spanish - Society #9", level: 4000 },
      { id: "eWskCwh-vy0", title: "Pickpocket - Intermediate Spanish - Illustrations #1", level: 4000 },
      { id: "GbDkWTx4mTg", title: "Debate: Dogs VS Cats - Intermediate Spanish - Debates #6", level: 4000 },
      { id: "Lwuh9sgdf_0", title: "Spanish History: Columbus - Intermediate Spanish - History #8", level: 4000 },
      { id: "mlgsubGlzB0", title: "The Story of the Lizard - Intermediate Spanish - Personal Stories #36", level: 4000 },
      { id: "odJZ0zUUpdk", title: "RPG: Desert Island (1/2) - Intermediate Spanish - Let's Play Games #5", level: 4000 },
      { id: "tx73qdbUk7s", title: "Should Spain Apologize to Mexico? - Intermediate Spanish - News #8", level: 4000 },
      { id: "XP-7D5P-Hfo", title: "What Pablo Was Like as a Child - Intermediate Spanish - Personal Stories #42", level: 4000 },
      { id: "2-X3gElcWYU", title: "My Favorite Thai Snack - Intermediate Spanish - Food #7", level: 5000 },
      { id: "2_XZLAh5f_s", title: "History Of Spain: The Reconquista - Intermediate Spanish - History #6", level: 5000 },
      { id: "_SETY9jDPn8", title: "Trip to La Gomera - Intermediate Spanish - Tourism & Travel #17", level: 5000 },
      { id: "maI32AEm1GU", title: "Enigma: Chess And Gun - Intermediate Spanish - Let's Play Games #14", level: 5000 },
      { id: "xz1WIT37_G0", title: "Debate: Mexico VS Spain - Intermediate Spanish - Debates #1", level: 5000 },
      { id: "XzLxoRS62DI", title: "Scene: Ordering Coffee - Intermediate Spanish - Scenes #1", level: 5000 },
      { id: "2NeDbJbRwxw", title: "🏙 City VS Countryside 🏡 - Intermediate Spanish - Debates #4", level: 6000 },
      { id: "4pAwCy3o53I", title: "History of Spain: Roman Hispania - Intermediate Spanish - History #3", level: 6000 },
      { id: "dmSuiLw5604", title: "Adrià's Daily Routine 1/2 - Intermediate Spanish - Daily Life #14", level: 6000 },
      { id: "iMxabjgE-iY", title: "Mom's Favorite Spanish Food - Intermediate Spanish - Food #9", level: 6000 },
      { id: "jtsvzfwy_Qw", title: "Karlos' House - Intermediate Spanish - Daily Life #30", level: 6000 },
      { id: "jXvnh1mudDM", title: "Indiana Jones and the Fate of Atlantis - Intermediate Spanish - Video Games #3", level: 6000 },
      { id: "My1BrIKUtJE", title: "I (try to) fix my phone (glorious ending) - Intermediate Spanish - How-To #4", level: 6000 },
      { id: "uMbqW-duvdc", title: "Story Game: Dream On - Intermediate Spanish - Let's Play Games #13", level: 6000 },
      { id: "x8FFvFfVP7c", title: "History Of Spain: The Arab Invasion - Intermediate Spanish - History #5", level: 6000 },
      { id: "DWmTTp4tX4s", title: "History of Spain: The Visigoths - Intermediate Spanish - History #4", level: 7000 },
      { id: "yHAVjuVtJ-4", title: "History of Spain: Prehistoric Times - Intermediate Spanish - History #2", level: 7000 },
      { id: "Fo3Fsq1PKdQ", title: "Spanish Rumba - Intermediate Spanish - Spanish Culture #15", level: 10000 }
    ],
    adv: [
      { id: "LDjkk6fWTQ8", title: "Meeting Friends - Advanced Spanish - Daily Life #41", level: 2000 },
      { id: "Tp_EZBYavWE", title: "Passwords - Advanced Spanish - Random Topics #14", level: 3000 }
    ]
  }
})